### ISSUE TITLE
Did not find config.json

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/omniview#42] opened 2023-10-23 08:34 UTC
The compiled version of the programm in windows has no config file. 

System: Windows 11
Version: b0a3756

 
![ConfigFile](https://github.com/skunkforce/omniview/assets/83161524/84a03c98-fe11-4e08-ba2b-7c3ae08fca7b)

**Comment by bjoekeldude** [comment] 2023-10-23 11:59
There are two possible fixes:

1. A standard config.json is generated during the compilation-process in CI
2. An empty config.json is generated on opening the application

Which entries in config.json are mandatory, @NP199?

**Comment by R-Abbasi** [comment] 2023-10-24 16:12
The program works well on Linux and a `config.json` file is created as soon as the cloning is done (the first step). It must be the same on Windows. So I suggest checking _omniview/config_ folder for that json file. You can manually copy it into _/omniview/build/config_ folder, after compiling the project, and retest. 
Since both _title_ and _size_ (_sizex, sizey_) entities are quite short, they'll be more easily dealt with when hardcoded, lesser loads of `load_json<...>(config, ...)` totally, and a little higher performance for the program likely, to me.

**Comment by NP199** [comment] 2023-10-25 08:37
The idea behind downloading the config.json was to simplify the usage of the programm. We want to ship the program to enduser with little knowledge of computer systems and their need to have files in the right directory.
When you clone the repository and build the thing on your own machine, than windows has no problem with that either.
The problem is when you drag the executable file somewhere else on your system and forget the config.json.

In my opninion it can`t be the solution to trust the user to do the right thing and move the config.json and language.json with them and there should be default handling wiht this as mentioned above.

So my suggestion would be to be able to run the program without these files, so it can be used atleast.
The idea with the CI is good aswell.

Another challenge we will be facing is to get the right version of the config with the right version of the program running. If we make major changes right now, the whole supporting process will be worse, because of the lacking version controll.

I hope i descripted the problems in a coprenhesible way.

**Comment by bjoekeldude** [comment] 2023-10-27 14:57
I think this issue should be closed and be handled as a duplicate of #21 
With the next major release - January - we should have decided on a process on how to deal with this.

**Closed by bjoekeldude** 2023-10-27 14:57 UTC
Labels: bug
